### ISSUE TITLE
[Question]: Installing on replit?

### ISSUE THREAD

**Issue by animecat7** [weeklyd3/nodb-forum#47]
### Your question

I know replit isn't a good idea and a nightmare, and i understand if you dont wanna fix this, but can you please help me

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

if you are still reading, thanks. Here is my problem:

-When I install it it doesn't create the config.json and it cant access PSW.txt (I can fix this one).

here is how i installed it:

>1. made a new repl: php web server
>2. deleted all premade files  (index.php)
>3. put into shell: git clone https://github.com/weeklyd3/nodb-forum.git --branch 0.0.3 (this clones your v0.0.3 release innstead of 
   entire repo)
>4. dragged all files and folders out of the nodb-forum folder that got created (I let the .replit overwrite the one that came with the new repl)
>5. hit the start button
>6. opened link in new tab (https://forum.littleclaw.repl.co/)

>7.saw the errors and was confused

```no config.json```
![Screenshot 2022-07-02 12 54 20 AM](https://user-images.githubusercontent.com/97673666/176992002-c9bb3d05-8a7d-4aef-97dc-57e03fedaeb3.png)
<br>
<br>
<br>

```everything out of the nodb-folder (deleted)```
![Screenshot 2022-07-02 12 52 46 AM](https://user-images.githubusercontent.com/97673666/176991974-ad9bfa5b-009b-45d2-842e-cec52f867538.png)
<br>
<br>
<br>

```shell command```
![Screenshot 2022-07-02 12 52 28 AM](https://user-images.githubusercontent.com/97673666/176991977-98c76036-dcc1-451f-8a71-5f9e95ee8d24.png)
<br>
<br>
<br>

```error on website```
![Screenshot 2022-07-02 12 52 12 AM](https://user-images.githubusercontent.com/97673666/176991979-bcb04dd6-87ac-4326-9405-f62aa9ecd91d.png)

### Version

0.0.3

**Comment by weeklyd3** [comment]
The thing that redirects to installation is a bit buggy. You can head to `/app/install.php` directly.

**Comment by animecat7** [comment]
thx

**Comment by weeklyd3** [comment]
No problem :)

**Comment by animecat7** [comment]
it still is missing some files and displaying errors
![Screenshot 2022-07-02 10 24 20 PM](https://user-images.githubusercontent.com/97673666/177026160-1357cd63-8124-44aa-8677-87529d5437a1.png)
![Screenshot 2022-07-02 10 23 55 PM](https://user-images.githubusercontent.com/97673666/177026161-2001dcfd-43f1-42b4-8479-5a89b0969dd7.png)

**Comment by weeklyd3** [comment]
ok, that looks like a bug there. I'll try to fix it

**Comment by weeklyd3** [comment]
The flags feature hasn't been very stable though. I might try.

**Comment by animecat7** [comment]
ok, thanks for the replit support

**Comment by Paragramex** [comment]
uh, sorry to bother you again
whats the password hashing, im making another login system

**Comment by weeklyd3** [comment]
Nothing too complicated. It's just <code>password_hash($password, PASSWORD_DEFAULT);</code> to hash and <code>password_verify($password, $hash);</code> to verify.

**Comment by Paragramex** [comment]
ok, thanks

**Comment by Paragramex** [comment]
lets say i wanted to view my users passwords, how would i do that?

**Comment by weeklyd3** [comment]
I'm sorry, but you can't. Hashing is one-way, and can't be reversed.

**Comment by Paragramex** [comment]
i mean like if I used post requests from one website to another

**Comment by weeklyd3** [comment]
I don't think that would be secure because then an attacker could see the passwords, but if you want to do that, you can put some code that intercepts the password (`$_POST['psw']`) and write it to a file somewhere.

**Comment by Paragramex** [comment]
ohhhhhhhhhhhhhhhhhhhh thx
i dont fully understand post and get in php but i think i could do this
